export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";
export const FETCH_NOTIFICATION_SUCCESS = "FETCH_NOTIFICATION_START";
export const FETCH_NOTIFICATION_START = "FETCH_NOTIFICATION_SUCCESS";
export const FETCH_NOTIFICATION_FAILED = "FETCH_NOTIFICATION_FAILED";
export const FETCH_NOTIFICATION_COUNT = "FETCH_NOTIFICATION_COUNT";
export const TOGGLE_NOTIFICATION = "TOGGLE_NOTIFICATION";
export const SHOW_MORE_NOTIFICATION = "SHOW_MORE_NOTIFICATION";
