export const FETCH_POSTS_START = "FETCH_POSTS_START";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILED = "FETCH_POSTS_FAILED";

export const FETCH_POST_START = "FETCH_POST_START";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILED = "FETCH_POST_FAILED";

export const POST_LIKE_START = "POST_LIKE_START";
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS";
export const POST_LIKE_FAILED = "POST_LIKE_FAILED";

export const ADD_COMMENT_START = "ADD_COMMENT_START";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILED = "ADD_COMMENT_FAILED";

export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";

export const DELETE_COMMENT_START = "DELETE_COMMENT_START";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILED = "DELETE_COMMENT_FAILED";

export const LIKE_COMMENTS = "LIKE_COMMENTS";

export const ADD_COMMENT_REPLAY_START = "ADD_COMMENT_REPLAY_START";
export const ADD_COMMENT_REPLAY_SUCCESS = "ADD_COMMENT_REPLAY_SUCCESS";
export const ADD_COMMENT_REPLAY_FAILED = "ADD_COMMENT_REPLAY_FAILED";

export const EDIT_COMMENT_REPLY_SUCCESS = "EDIT_COMMENT_REPLY_SUCCESS";

export const DELETE_COMMENT_REPLY_START = "DELETE_COMMENT_REPLY_START";
export const DELETE_COMMENT_REPLY_SUCCESS = "DELETE_COMMENT_REPLY_SUCCESS";
export const DELETE_COMMENT_REPLY_FAILED = "DELETE_COMMENT_REPLY_FAILED";

export const LIKE_COMMENTS_REPLY = "LIKE_COMMENTS_REPLY";
